.nds
.thumb

// Auto-generated by tools/randomizer/generate_species_map.py. Do not edit.
.macro RANDOMIZER_STARTER_CHOICES
    .word 152 // SPECIES_CHIKORITA
    .word 155 // SPECIES_CYNDAQUIL
    .word 158 // SPECIES_TOTODILE
.endmacro
